name: macos-p7zip-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: macos-Check
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: build 7za & check
      run: |
        brew install patchelf
        patchelf --version
        mkdir macos-p7zip
        mkdir macos-p7zip/bin
        mkdir macos-p7zip/lib
        export PROJECT_ROOT=`pwd`
        cd CPP/7zip/Bundles/Alone
        make -f makefile.gcc
        INSTALL_PREFIX=$PROJECT_ROOT/macos-p7zip make -f makefile.gcc install
        # git clone  https://github.com/jinfeihan57/p7zip_test_utils.git
        # cd p7zip_test_utils/check
        # bash check_7za.sh $PROJECT_ROOT/macos-p7zip/bin/7za
    - name: build 7zz & check
      run: |
        export PROJECT_ROOT=`pwd`
        cd CPP/7zip/Bundles/Alone2
        make -f makefile.gcc
        INSTALL_PREFIX=$PROJECT_ROOT/macos-p7zip make -f makefile.gcc install
        git clone  https://github.com/jinfeihan57/p7zip_test_utils.git
        cd p7zip_test_utils/check
        bash check.sh $PROJECT_ROOT/macos-p7zip/bin/7zz
    - name: build 7z.so
      run: |
        export PROJECT_ROOT=`pwd`
        cd CPP/7zip/Bundles/Format7zF
        make -f makefile.gcc
        INSTALL_PREFIX=$PROJECT_ROOT/macos-p7zip make -f makefile.gcc install
